services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    # volumes:
    #   - kafka_data:/tmp/kraft-combined-logs
    healthcheck:
      test: ["CMD", "nc", "-z", "127.0.0.1", "9092"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  producer:
    build:
      context: ./producers
    container_name: producer
    image: producer:0.0.1-pagseguro
    environment:
      PRODUCER_MAX_INTERVAL: ${PRODUCER_MAX_INTERVAL:-5}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS:-kafka:9092}
      KAFKA_TOPIC: ${KAFKA_TOPIC:-orders}
      LIMIT_NUM_ORDERS: ${LIMIT_NUM_ORDERS:-10000000}
    depends_on:
      kafka:
        condition: service_healthy

volumes:
  kafka_data:
  mongodb_data:
